// datos para gráfica de carrera por año: https://codepen.io/anattolia/pen/NWQOpzW
const allData = {
    "1987": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1988": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1989": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1990": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1991": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1992": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1993": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1994": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1995": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1996": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1997": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1998": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "1999": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2000": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 1 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2001": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2002": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 2 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2003": [
        { "indicador": "Políticas Educativas", "MAU": 1 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2004": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 2 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 1 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2005": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 2 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 1 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2006": [
        { "indicador": "Políticas Educativas", "MAU": 1 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 1 },
        { "indicador": "Estudios Interculturales", "MAU": 1 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2007": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 2 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2008": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 2 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 2 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 1 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2009": [
        { "indicador": "Políticas Educativas", "MAU": 1 },
        { "indicador": "Educación", "MAU": 1 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 1 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 7 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 1 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 1 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 2 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2010": [
        { "indicador": "Políticas Educativas", "MAU": 4 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2011": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 1 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 2 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 1 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2012": [
        { "indicador": "Políticas Educativas", "MAU": 3 },
        { "indicador": "Educación", "MAU": 5 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 2 },
        { "indicador": "Transformación Digital", "MAU": 1 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 1 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 1 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 1 }
    ],
    "2013": [
        { "indicador": "Políticas Educativas", "MAU": 4 },
        { "indicador": "Educación", "MAU": 7 },
        { "indicador": "Pedagogía", "MAU": 2 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 1 }
    ],
    "2014": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 1 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 4 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 1 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2015": [
        { "indicador": "Políticas Educativas", "MAU": 5 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 2 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 1 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 3 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2016": [
        { "indicador": "Políticas Educativas", "MAU": 3 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 1 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 3 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2017": [
        { "indicador": "Políticas Educativas", "MAU": 4 },
        { "indicador": "Educación", "MAU": 3 },
        { "indicador": "Pedagogía", "MAU": 1 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 1 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 2 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 2 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 2 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU":1 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2018": [
        { "indicador": "Políticas Educativas", "MAU": 3 },
        { "indicador": "Educación", "MAU": 5 },
        { "indicador": "Pedagogía", "MAU": 2 },
        { "indicador": "Formacion", "MAU": 5 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 4 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 3 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 1 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 1 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 1 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2019": [
        { "indicador": "Políticas Educativas", "MAU": 1 },
        { "indicador": "Educación", "MAU": 4 },
        { "indicador": "Pedagogía", "MAU": 3 },
        { "indicador": "Formacion", "MAU": 3 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 2 },
        { "indicador": "Didáctica", "MAU": 1 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 2 },
        { "indicador": "Transformación Digital", "MAU": 2 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 1 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 2 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 3 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 1 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 1 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2020": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 2 },
        { "indicador": "Pedagogía", "MAU": 2 },
        { "indicador": "Formacion", "MAU": 1 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 1 },
        { "indicador": "Didáctica", "MAU": 1 },
        { "indicador": "Currículo", "MAU": 1 },
        { "indicador": "Docencia", "MAU": 1 },
        { "indicador": "Transformación Digital", "MAU": 1 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 1 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 1 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 1 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2021": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 7 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 1 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 1 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 3 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 1 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 1 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 1 },
        { "indicador": "Acceso a Educación Superior", "MAU": 0 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 1 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2022": [
        { "indicador": "Políticas Educativas", "MAU": 2 },
        { "indicador": "Educación", "MAU": 8 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 1 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 1},
        { "indicador": "Transformación Digital", "MAU": 0 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 1 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 2 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 3 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2023": [
        { "indicador": "Políticas Educativas", "MAU": 5 },
        { "indicador": "Educación", "MAU": 9 },
        { "indicador": "Pedagogía", "MAU": 3 },
        { "indicador": "Formacion", "MAU": 2 },
        { "indicador": "Estudios Interculturales", "MAU": 2 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 3 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 4 },
        { "indicador": "Transformación Digital", "MAU": 2 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 1 },
        { "indicador": "Innovación Pedagogica", "MAU": 2 },
        { "indicador": "Innovación Academica", "MAU": 2 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 1 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 2 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 1 },
        { "indicador": "Bienestar Universitario", "MAU": 1 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
    "2024": [
        { "indicador": "Políticas Educativas", "MAU": 0 },
        { "indicador": "Educación", "MAU": 0 },
        { "indicador": "Pedagogía", "MAU": 0 },
        { "indicador": "Formacion", "MAU": 0 },
        { "indicador": "Estudios Interculturales", "MAU": 0 },
        { "indicador": "Enseñanza Aprendizaje", "MAU": 0 },
        { "indicador": "Didáctica", "MAU": 0 },
        { "indicador": "Currículo", "MAU": 0 },
        { "indicador": "Docencia", "MAU": 0 },
        { "indicador": "Transformación Digital", "MAU": 1 },
        { "indicador": "Internacionalización", "MAU": 0 },
        { "indicador": "Deserción", "MAU": 0 },
        { "indicador": "Construcción de conocimiento", "MAU": 0 },
        { "indicador": "Innovación Pedagogica", "MAU": 0 },
        { "indicador": "Innovación Academica", "MAU": 0 },
        { "indicador": "Evaluación", "MAU": 0 },
        { "indicador": "Universidades Públicas", "MAU": 0 },  
        { "indicador": "Proyección", "MAU": 0 },
        { "indicador": "Conectividad", "MAU": 0 },
        { "indicador": "Calidad Educativa", "MAU": 0 },
        { "indicador": "Estrategias de Estudio", "MAU": 0 },
        { "indicador": "Acceso a Educación Superior", "MAU": 1 },
        { "indicador": "Organizaciones Estudiantiles", "MAU": 0 },
        { "indicador": "Agresión Escolar", "MAU": 0 },
        { "indicador": "Bienestar Universitario", "MAU": 0 },
        { "indicador": "Escuela Nueva", "MAU": 0 }
    ],
}